"""Adapter-first classification for trusted shared CLIs.

This module never executes a command.  It turns a narrowly supported,
standalone shell surface into immutable argv and routing metadata.  Unknown or
compound syntax remains outside the managed identity control plane.
"""

from __future__ import annotations

import re
import shlex
from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path
from urllib.parse import urlsplit


class ManagedCliRoute(StrEnum):
    INSTALLER = "installer"
    PROVIDER = "provider_runner"
    BROWSER_AUTH = "browser_auth_runner"


class ManagedCliAction(StrEnum):
    INSTALL = "install"
    LOCAL_INSPECTION = "local_inspection"
    CREDENTIAL_READ = "credential_read"
    CREDENTIAL_WRITE = "credential_write"
    PROVIDER_OPERATION = "provider_operation"
    BROWSER_AUTH = "browser_auth"


@dataclass(frozen=True)
class ManagedCliMatch:
    adapter_id: str
    action: ManagedCliAction
    route: ManagedCliRoute
    argv: tuple[str, ...]
    env: tuple[tuple[str, str], ...] = ()
    provider: str | None = None
    requires_profile: bool = False
    requires_network: bool = False
    workspace_writable: bool = False
    distribution: str | None = None


class UnsupportedManagedCliCommand(ValueError):
    """A managed executable was mentioned using an unsafe/unknown shape."""


_ENV_ASSIGNMENT = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)=(.*)$", re.DOTALL)
_LARK_ALLOWED_ENV = frozenset(
    {
        "LARKSUITE_CLI_NO_SKILLS_NOTIFIER",
        "LARKSUITE_CLI_NO_UPDATE_NOTIFIER",
    }
)
_LARK_PACKAGE = re.compile(r"^@larksuite/cli(?:@([0-9A-Za-z][0-9A-Za-z.+_-]*))?$")
_SHELL_CONTROL = re.compile(r"(?:\n|\r|`|\$\(|\$\{|[;&|<>])")


def _standalone_argv(command: str) -> tuple[list[str], dict[str, str]] | None:
    value = str(command or "").strip()
    value = re.sub(r"\s+2\s*>\s*&\s*1\s*$", "", value)
    if not value or _SHELL_CONTROL.search(value):
        return None
    try:
        tokens = shlex.split(value, posix=True)
    except ValueError:
        return None
    if not tokens:
        return None
    if tokens[0] == "command":
        tokens = tokens[1:]
    if tokens[:1] == ["env"]:
        tokens = tokens[1:]
    env: dict[str, str] = {}
    while tokens:
        assignment = _ENV_ASSIGNMENT.fullmatch(tokens[0])
        if assignment is None:
            break
        env[assignment.group(1)] = assignment.group(2)
        tokens = tokens[1:]
    return (tokens, env) if tokens else None


def _npm_lark_install(tokens: list[str], env: dict[str, str]) -> ManagedCliMatch | None:
    if env or not tokens or Path(tokens[0]).name.lower() != "npm":
        return None
    args = tokens[1:]
    if not args or args[0].lower() not in {"install", "add", "i"}:
        return None
    global_seen = False
    packages: list[str] = []
    index = 1
    while index < len(args):
        token = args[index]
        lowered = token.lower()
        if lowered in {"-g", "--global"}:
            global_seen = True
        elif lowered in {"--save", "--no-save", "--ignore-scripts"}:
            # ``--ignore-scripts`` is accepted but not generated by the Lark
            # adapter; npm still needs the package's own bin linking.
            pass
        elif lowered.startswith("-"):
            return None
        else:
            packages.append(token)
        index += 1
    if not global_seen or len(packages) != 1 or _LARK_PACKAGE.fullmatch(packages[0]) is None:
        return None
    return ManagedCliMatch(
        adapter_id="lark-cli",
        action=ManagedCliAction.INSTALL,
        route=ManagedCliRoute.INSTALLER,
        argv=("npm", "install", "--global", packages[0]),
        requires_network=True,
        distribution=packages[0],
    )


def _claims_unregistered_toolchain_mutation(tokens: list[str]) -> bool:
    if not tokens:
        return False
    executable = Path(tokens[0]).name.lower()
    lowered = [item.lower() for item in tokens[1:]]
    if executable in {"npm", "pnpm", "yarn"}:
        return any(item in {"-g", "--global"} for item in lowered) and any(
            item in {"install", "add", "i", "remove", "uninstall", "update", "upgrade"}
            for item in lowered
        )
    if executable == "pipx":
        return bool(lowered and lowered[0] in {"install", "uninstall", "upgrade", "upgrade-all"})
    if executable == "uv":
        return bool(lowered[:1] == ["tool"] and len(lowered) > 1 and lowered[1] in {"install", "uninstall", "upgrade"})
    if executable == "cargo":
        return bool(lowered[:1] == ["install"])
    return False


def _lark_command(tokens: list[str], env: dict[str, str]) -> ManagedCliMatch | None:
    if not tokens or Path(tokens[0]).name.lower() != "lark-cli":
        return None
    if any(name not in _LARK_ALLOWED_ENV for name in env):
        raise UnsupportedManagedCliCommand("unsupported environment variable for managed lark-cli")
    if any(value not in {"1", "true"} for value in env.values()):
        raise UnsupportedManagedCliCommand("managed lark-cli environment flags must use a fixed enabled value")
    argv = tuple(["lark-cli", *tokens[1:]])
    lowered = [item.lower() for item in tokens[1:]]
    if any(item == "--profile" or item.startswith("--profile=") for item in lowered):
        raise UnsupportedManagedCliCommand(
            "lark-cli --profile is controlled by PuddingClaw Credential Profile selection"
        )
    if "--yes" in lowered or "-y" in lowered:
        raise UnsupportedManagedCliCommand(
            "lark-cli confirmation flags are added only by the managed high-risk action flow"
        )
    if not lowered or any(item in {"-h", "--help"} for item in lowered) or lowered[0] in {
        "help",
        "version",
        "--version",
        "schema",
    }:
        return ManagedCliMatch(
            adapter_id="lark-cli",
            action=ManagedCliAction.LOCAL_INSPECTION,
            route=ManagedCliRoute.PROVIDER,
            argv=argv,
            env=tuple(sorted(env.items())),
        )
    if lowered[:2] == ["config", "init"] and lowered != ["config", "init", "--new"]:
        raise UnsupportedManagedCliCommand(
            "managed lark-cli config init requires the exact --new form"
        )
    if lowered == ["config", "init", "--new"]:
        return ManagedCliMatch(
            adapter_id="lark-cli",
            action=ManagedCliAction.BROWSER_AUTH,
            route=ManagedCliRoute.BROWSER_AUTH,
            argv=argv,
            env=tuple(sorted(env.items())),
            provider="lark",
            requires_profile=True,
            requires_network=True,
        )
    if lowered[:2] == ["auth", "qrcode"]:
        if len(tokens) < 4:
            raise UnsupportedManagedCliCommand("managed lark-cli auth qrcode requires a URL")
        try:
            parsed_url = urlsplit(tokens[3])
        except ValueError as exc:
            raise UnsupportedManagedCliCommand("managed lark-cli auth qrcode URL is invalid") from exc
        if (
            parsed_url.scheme.lower() not in {"http", "https"}
            or not parsed_url.hostname
            or parsed_url.username
            or parsed_url.password
        ):
            raise UnsupportedManagedCliCommand("managed lark-cli auth qrcode requires an HTTP(S) URL")
        output_paths: list[str] = []
        index = 4
        while index < len(tokens):
            item = tokens[index]
            if item == "--ascii":
                index += 1
                continue
            if item == "--output" and index + 1 < len(tokens):
                output_paths.append(tokens[index + 1])
                index += 2
                continue
            if item.startswith("--output="):
                output_paths.append(item.partition("=")[2])
                index += 1
                continue
            raise UnsupportedManagedCliCommand("unsupported managed lark-cli auth qrcode option")
        for raw_path in output_paths:
            path = Path(raw_path)
            if path.is_absolute() or ".." in path.parts:
                raise UnsupportedManagedCliCommand("lark-cli QR output must stay inside the workspace")
        return ManagedCliMatch(
            adapter_id="lark-cli",
            action=ManagedCliAction.LOCAL_INSPECTION,
            route=ManagedCliRoute.PROVIDER,
            argv=argv,
            env=tuple(sorted(env.items())),
            workspace_writable=bool(output_paths),
        )
    if lowered[:2] == ["auth", "login"]:
        if "--device-code" in lowered:
            device_index = lowered.index("--device-code")
            if device_index + 1 >= len(lowered) or device_index + 2 != len(lowered):
                raise UnsupportedManagedCliCommand(
                    "managed lark-cli device-code completion requires exactly one device code"
                )
            return ManagedCliMatch(
                adapter_id="lark-cli",
                action=ManagedCliAction.CREDENTIAL_WRITE,
                route=ManagedCliRoute.PROVIDER,
                argv=argv,
                env=tuple(sorted(env.items())),
                provider="lark",
                requires_profile=True,
                requires_network=True,
            )
        if "--no-wait" not in lowered or "--json" not in lowered:
            raise UnsupportedManagedCliCommand(
                "managed lark-cli auth login initiation requires --no-wait --json so browser authorization can pause the Agent turn"
            )
        return ManagedCliMatch(
            adapter_id="lark-cli",
            action=ManagedCliAction.BROWSER_AUTH,
            route=ManagedCliRoute.BROWSER_AUTH,
            argv=argv,
            env=tuple(sorted(env.items())),
            provider="lark",
            requires_profile=True,
            requires_network=True,
        )
    if lowered[:2] in (["config", "remove"], ["auth", "logout"]):
        action = ManagedCliAction.CREDENTIAL_WRITE
    elif lowered[:2] in (["config", "show"], ["auth", "status"]):
        action = ManagedCliAction.CREDENTIAL_READ
    elif lowered[:1] == ["update"]:
        raise UnsupportedManagedCliCommand(
            "lark-cli update must be performed through the managed installer"
        )
    else:
        action = ManagedCliAction.PROVIDER_OPERATION
    workspace_writable = any(
        item in {"download", "export", "save", "output"}
        or item.startswith(("--output=", "--out="))
        for item in lowered
    )
    return ManagedCliMatch(
        adapter_id="lark-cli",
        action=action,
        route=ManagedCliRoute.PROVIDER,
        argv=argv,
        env=tuple(sorted(env.items())),
        provider="lark",
        requires_profile=True,
        requires_network=True,
        workspace_writable=workspace_writable,
    )


class ManagedCliRegistry:
    """Registry of Backend-owned adapters.

    Ordinary Skills and remote Markdown cannot mutate this registry.
    """

    _CLAIMED = re.compile(r"(?:^|\s|['\"])(?:[^\s'\"]*/)?lark-cli(?:\s|$|['\"])", re.IGNORECASE)

    def match(self, command: str) -> ManagedCliMatch | None:
        parsed = _standalone_argv(command)
        if parsed is None:
            if self.claims(command):
                raise UnsupportedManagedCliCommand(
                    "managed lark-cli commands must be standalone argv without pipes, redirects, or shell composition"
                )
            return None
        tokens, env = parsed
        install = _npm_lark_install(tokens, env)
        if install is not None:
            return install
        lark = _lark_command(tokens, env)
        if lark is not None:
            return lark
        if _claims_unregistered_toolchain_mutation(tokens):
            raise UnsupportedManagedCliCommand(
                "user-level CLI installation is Adapter-first; this distribution has no trusted ManagedCliAdapter"
            )
        if self.claims(command):
            raise UnsupportedManagedCliCommand(
                "managed lark-cli commands cannot be hidden behind wrappers or shell arguments"
            )
        return None

    def claims(self, command: str) -> bool:
        return bool(self._CLAIMED.search(str(command or "")))
